### ISSUE TITLE
Events dropped when using large ROI size

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#16]
Shape-In 2.3.3.54

During a measurement, I noticed that there are events being dropped in regular intervals:
![measurement_breaks](https://user-images.githubusercontent.com/75362246/162215363-1fe5c25d-0d55-4efd-a5b7-8371ecb2ec9c.png)

It seems that around 1000 - 1500 events are detected and then a short break occurs, during which no events are detected/saved.
I measured with a manual ROI size of 740 px x 100 px, at a frame rate of 4000 fps with fluorescence, the event rate was roughly 400 events per seconds.
The ROI is roughly 3 times bigger compared to a standard ROI size, but as the event rate was also roughly 2-3 times lower than what is possible (1000 events per seconds), I was hoping this is no issue. Although, maybe the measurement actually is running with 1000 events per second and since that is too much to handle, Shape-In drops some events and displays only the number of events that were actually saved, thus ending up at around 400 events/s?

From what I saw in Windows Task Manager, the RAM and CPU usage was below 20 % during the measurement, while the HDD transfer rates were roughly 70 MB/s, so I would suspect the hardware is not an issue.

**Comment by phidahl** [comment]
This is expected behaviour. ShapeIn drops events if the imaging queue gets too full. This causes the gaps in data.
Larger ROI increase load and reduce the number of frames/events that can be processed in time. Because of the architecture ShapeIn won't saturate all CPU cores.

By the way: Using this large ROI with fluorescence most likely won't work properly.
