### ISSUE TITLE
Background correction leads to white line in center of channel

### ISSUE THREAD

**Issue by marketakub** [ZELLMECHANIK-DRESDEN/ShapeIn_Issues#5]
Measurements of blood (sample fluid prepared as usual 50 ul blood + 950 ul 0.6% MC) at the clinics are now done with continuous background storage, with the image_bg feature. Without background correction the images look OK, but when BGR correction is applied there is a white line in the center.

![cell4subtr](https://user-images.githubusercontent.com/46028267/113883962-e9619900-97be-11eb-875e-d907596ab9fb.JPG)
![cell4subtr](https://user-images.githubusercontent.com/46028267/113883965-e9fa2f80-97be-11eb-9045-db5a0608c9e3.png)
![cell5](https://user-images.githubusercontent.com/46028267/113883967-e9fa2f80-97be-11eb-808e-1dd110a81712.png)
![cell5subtr](https://user-images.githubusercontent.com/46028267/113883969-ea92c600-97be-11eb-8fd9-af129759d96b.png)

**Comment by paulmueller** [comment]
EDIT: wrong repository.
@phidahl are you subscribed to the issues here?

**Comment by phidahl** [comment]
@paulmueller yes

Dark RBCs darken the background. But brightness is computed without bg correction so it should be unaffected.
As long as the line in the bg does not affect contour detection it is not causing other problems?

Especially in blood measurements it would be hard to find frames without RBCs.

**Comment by paulmueller** [comment]
Background-corrected images could be used for haralick texture features, focus estimation, or machine learning, where e.g. the channel walls and imaging artifacts change the plain cell image.

Why are there images of red blood cells in the background frames? Does Shape-In not detect them? Or does Shape-In compute the background from **all** images (regardless of whether they contain events or not)? Could this behavior be changed?

**Comment by paulmueller** [comment]
@phidahl Adding to our off-the-record discussion, I think it would be good of Shape-In would log any issues it encounters (e.g. "Warning: No usable background frames for the past 60s!" or so) to its log (#6) or a separate log (e.g. "Shape-In warnings"). I think we should also add an HDF5 metadata key if the option we discussed was enabled - I propose `"online_contour:bg empty" = True` (`False` would be the current situation). What do you think?

**Comment by phidahl** [comment]
This will be implemented as suggested.
About the warnings: 1 s would be already too much for no new background image. I will append one warning in the end that says something about how often there where no empty frames available.
There will be to categories for shapein logs in the hdf5 file: logs/shapein-acquisition and logs/shapein-warning

**Comment by phidahl** [comment]
The warning message created at the end of the measurement would be: 
"logs/shapein-warning": "[WARNING] 12:01:08.187 Forced background image aggregations: 3869 times"
If one or more times a frame with object(s) was taken for the background calculation. This should happen for very dense samples.

**Comment by maxschloegel** [comment]
@phidahl and @paulmueller during internal discussion about the background correction the question came up, how exactly the background images are computed/generated, also because we were curious about the white line in the middle of the channel after background correction. I saw that you discussed it off-the-record, is there an official answer to that?

**Comment by paulmueller** [comment]
There are two ways of computing the background image since Shape-In 2.2.2.5:

1. Take the rolling mean of **all** frames (including event images). This is the old behavior.
2. Take the rolling mean of those frames that do not contain any events. This mode has to be manually enabled (it is a hidden setting). It might occur, that there are no frames without events available in which case the above-mentioned warnings are written to the HDF5 file.

Shape-In sets the "online_contour:bg empty" key according to the option you chose:

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/b4f09df85e6dac83c18daf1bc99211e88bc651d2/dclab/definitions.py#L106-L111
